application:
  service:
    name: eurekaclient
management:
  security:
    enabled: false
server:
  port: 8090
message:
  act: "Hello billing service"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
