server:
  port: 8090

message:
  act: "Hello billing service"

management:
  security:
    enabled: false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
