application:
  service:
    name: billing-service
data:
  rest:
    base-path: /api
management:
  security:
    enabled: false
server:
  port: 8090
message:
  act: "Hello billing service"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://${ZIPKIN_HOSTNAME:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8889}/eureka/
