spring:
  application:
    name: eureka-server1
eureka:  
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false 
