spring:
  application:
    name: eureka-server
  zipkin:
    baseUrl: http://${ZIPKIN_HOSTNAME:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1
eureka:  
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false 
