server:
  port: ${ZUUL_PORT:80}  
spring:
  application:
    name: gateway-mservice
  zipkin:
    baseUrl: http://${ZIPKIN_HOSTNAME:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  sensitive-headers: Cookie,Set-Cookie
  prefix: /api
  routes:
    billing:
      path: /billing/**
      serviceId: billing-service
      stripPrefix: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8889}/eureka/
      
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
